language: java

jdk:
  - openjdk16
  - openjdk15
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
  - secure: aJybO/NePIbl+T8wbxeo92RpW9Ssr+huxbEzof3zH9Dmd1XEMv+oMVEQCTOU1sD1b0o+LqwxIa6rRUTiIm+OCnxzbXuRcLz3b1I+qS05K1apqf3xb6svjjMioChm/WXvhRmM7Q7ZDT95j0jLt4fGUoI6qgh4U8L9TFTKdM6kZpUCV1oiqFLsE6QQZdrUzynLycJydmEc7SHfXqnOEj1qSdJaaUfLpJSmlGpz68h/0cMGelsWP6dNJ8a6c1eXLpgH8fJkoyeOL+Hsr6NXEaF1KRgcIAoKmA/kTFcfCA8i81n6bOzE52kxRtS7ehPCiOzr9YayDO9JPIvGIXUDZI8tX/zPFOvp6HMCVcQ9DHnFwuDYe7a6WNRw+6h3KecLj8myqLrbZrybihrJIWHbzp7LZ0nRSnsCp82iqOeKJ43VWWhxPGjfaYbZoXZajBcN3x6PMvVMjjwSY7fzH90E8OFf+aYeV4ww+9PhlTsqNWQCF/5gu87AV4dzXG1GXxVSUcuTZg2wYqwz4bKDQCb2mshd8E97dP407jSmbP5+L4AIdSaCo/kWarGiILGUylP9G/DXiFRMLPIorYqGGW6K7m0Sf+955t8WUbGz8hK6VKu7kndr770yWGWhc7V4QwNMj03AQANepYP+WiuW1C0RqmV35gxCeAKSWrFjK/fpaWVTf4o=
  - secure: RlPIkR+MYxJumBIDv8ZY4i9cJhGybygnDvRqn/j5QibG3gdAQRRdvsBLHtHPv7WjvpOWLSENhkVRMwJZT/78A9lnOL9eZq4honHlsRmKduVuzI5KYdycWBoB1W1bJ7C/qfMfklW5YkZDgxYsalymPgQ8rXOvJNKtx8ANywB+pRL8e/CKUK6TTXwrUHXZRZa8hee9vlhhTq06SK3LeFiC6chOB3J/RWDnPyktLj6B+iNe6LpWJjcwGJc58zBLm7iDqJbRkhJaKABziaDRsAPW3qPtmDA1WZ1iAwF6fsVGwxFJAxx1L9PA1DvJAYfB+9emFojmr1aHHyuGieIt4JV5sJyYv4tz9/fCAW3f1QJMl1x4btBdb/dJUf1E6LvNpy/0RtT1FYxAg2GbmcJjqCCNWp13gIdTH+d2wRrplFBXUgiffsu52rTynIxmM0El2cz8T11IOZFDsVr/q3XUZZPicmHE0hD8T43RrkA/5xnA9xt/AQd3HuN30N0t0qbrClmi9d0udE0njDUGLWhOphKzSfIGMmrxNFmNVgVp77bGLRLGOkOT4jhXy4UFQmrcHR33DOLGqWrZjSkUtlb/M1WGysWOpoilUqX3MDbQNAlKBvlLZdUU3Eb0Yrhtc5GKlg02/z+eMeW8ArQi2LXVVIX8HxQs7ZdgXt27WkLeuXMnW9M=
